### ISSUE TITLE
Request for more codes

### ISSUE THREAD

**Issue by Cccjl219** [LFhase/FeAT#1]
Great work! I am trying to reproduce your work. It seems that there are not codes of IRMX and IB-IRM methods in this repo. Can you provide more codes? Thx.

**Comment by LFhase** [comment]
Hi @Cccjl219 Thank you for your interest in our work! Apologize for missing the codes for IRMX and IB-IRM. I've updated the repo with [the commit](https://github.com/LFhase/FeAT/commit/55ca255df4107cb000768994ff947a5f7c8e85d5). Could you try it and let me know if it works?
